---
title: "2024_09_03"
output: html_document
date: "2024-09-03"
---

Day1 Morning:
```{r}
#load tidyverse
library(tidyverse)
library(ggplot2)


#Load the GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt file 
read_tsv("/data/learn/qb24/GTEx/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")

#assign to variable df
df = read_tsv("/data/learn/qb24/GTEx/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
```


```{r}
#Create a SUBJECT column using the following code
 df <- df %>%
    mutate( SUBJECT=str_extract( SAMPID, "[^-]+-[^-]+" ), .before=1 )

#Confirm that the first column in df is SUBJECT
head(df)
```


```{r}
#Which two SUBJECTs have the most samples? The least?
#Use group_by(), summarize(), and arrange()

#the most
df %>%
  group_by(SUBJECT) %>%
  summarize(n())  %>%
  arrange(`n()`)

#the least
df %>%
  group_by(SUBJECT) %>%
  summarize(n())  %>%
  arrange(desc(`n()`))
  
```


```{r}
#Which two SMTSDs (tissue types) have the most samples? The least? Why?

#the most
df %>%
  group_by(SMTSD) %>%
  summarize(n()) %>%
  arrange(desc(`n()`))

#the least
df %>%
  group_by(SMTSD) %>%
  summarize(n()) %>%
  arrange(`n()`)
```


```{r}
#For subject GTEX-NPJ8
#Filter for samples from this subject and save as a new object (e.g. df_npj8)

df_npj8 <- filter(df, SUBJECT == "GTEX-NPJ8")

df_npj8 %>%
  group_by(SMTSD) %>%
  summarize(n()) %>%
  arrange(desc(`n()`))
  
```



```{r}
#Explore SMATSSCR (autolysis score)

#Filter out NA values in this column to avoid mean() returning NA
#How many SUBJECTs have a mean SMATSSCR score of 0

df %>%
  group_by(SMATSSCR) %>%
  filter(!is.na(SMATSSCR)) %>%
  summarize (n()) %>%
  arrange(`n()`)
```


Day1 Afternoon:

Penguin data
```{r}
#library(tidyverse)
#install.packages('palmerpenguins')
#install.packages('ggthemes')
#library(ggthemes)
#library(palmerpenguins)

glimpse(penguins)
penguins
?penguins

#indexing the data, rows first them columns
#extract island column = all rows, island column
penguins[ , "island"]

#extract species and island
penguins[ , c("species", "island")]

#look at second observation
penguins[ 2 , c("species", "island")]

#same thing but with numbers
penguins[ 2 , 2]

```

Penguin data
```{r}
#library(palmerpenguins)
#library(ggplot2)


ggplot(data = penguins) +
  geom_point(mapping = aes(x = flipper_length_mm, 
                     y = body_mass_g, 
                     color = species,
                     shape = species)) +
  scale_color_colorblind() +
  #scale_color_manual(values = c("orange", "lightblue", "pink")) +
  geom_smooth(mapping = aes(x = flipper_length_mm, 
                     y = body_mass_g), method = "lm") +
  xlab("Flipper length (mm)") +
  ylab("Body mass (g)") +
  ggtitle("Relationship between body mass and flipper length \nin Antarctic Penguins")

#ggsave(filename = "~/qbb24-answers/d1-afternoon/penguin-plot.pdf")

```

Panguin data
```{r}
#does bill length depend on sex of penguin
#distribution of a continuous variable

#ggplot(data = penguins %>% filter(sex == "male"), mapping = aes( x = bill_length_mm))+
#  geom_histogram()

# to plot side by side facet_grid(. ~ sex)

ggplot(data = penguins, 
       mapping = aes( x = bill_length_mm, fill = sex))+
  scale_fill_colorblind() +
  geom_histogram(position = "identity", alpha = 0.5)


ggplot(data = penguins %>% filter(!is.na(sex)),
       mapping = aes( x = bill_length_mm, fill = sex))+
  scale_fill_colorblind() +
  geom_histogram(position = "identity", alpha = 0.5) +
  facet_grid(sex ~ species)

#body mass over time
ggplot( data= penguins, mapping = aes(x = factor(year), 
                                      y = body_mass_g, 
                                      fill = sex)) +
  scale_fill_colorblind() +
  geom_boxplot() +
  facet_grid(island ~ species)
```


Afternoon assignment: 

Q1 and Q2
```{r}
#Load tidyverse, use read_delim() to read in sample-level metadata that was obtained from the GTEx Portal

#read_delim("/data/learn/qb24/GTEx/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")

#this will show the first ~10 lines 
head(df)

#this will show more of the data and all the data categories
glimpse(df)
```

Q3 and Q4
```{r}
#Use the filter() function to subset the dataset to only the RNA-seq data by selecting rows for which the SMGEBTCHT column contains the value "TruSeq.v1". TruSeq is a library preparation kit from Illumina.

df_TruSeq = df  %>%
  filter(SMGEBTCHT == "TruSeq.v1")

#Plot the number of samples from each tissue (SMTSD) as a barplot. 
library(ggplot2)

# don't specify a 'y =' and R will do stat = count
ggplot(data= df_TruSeq, 
       mapping = aes(x = SMTSD))+
  geom_bar() +
  xlab("Tissue type") +
  ylab("Sample count") +

  theme(axis.text=element_text(size=10, color="black"),
        axis.text.x=element_text(angle = 90),
        axis.title=element_text(size=13),
        axis.line = element_line(color="black"),
        axis.ticks = element_line(color = "black", size =0.6),
        axis.ticks.length=unit(.15, "cm"),
        plot.title = element_text(size=13, hjust=0.5),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background = element_blank(),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.background = element_blank())

```

Q5
```{r}
#Plot the distribution of RNA integrity numbers across your samples. What type of plot is best for visualizing a single continuous distribution? 

#RIN heading is called SMRIN

# a histsogram is the best way to visualize a single continuous distribution
ggplot(data = df_TruSeq, mapping = aes (x = SMRIN))+
  geom_histogram() +
  xlab("RIN scores") +
  ylab("Sample count") +
  
  theme(axis.text=element_text(size=10, color="black"),
        axis.title=element_text(size=13),
        axis.line = element_line(color="black"),
        axis.ticks = element_line(color = "black", size =0.6),
        axis.ticks.length=unit(.15, "cm"),
        plot.title = element_text(size=13, hjust=0.5),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background = element_blank(),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.background = element_blank())

#the shape of the distribution is unimodal with most samples having an RIN between 6 and 8. Fewer samples have an RIN above 8. 
```

Q6
```{r}
#Copy your code from above, but now plot the distribution of RIN, stratified by tissue

ggplot(data = df_TruSeq, mapping = aes (x = SMRIN, fill = SMTSD))+
  geom_histogram(position = "identity") +
  xlab("RIN scores") +
  ylab("Sample count") +
  
  theme(axis.text=element_text(size=10, color="black"),
        axis.title=element_text(size=13),
        axis.line = element_line(color="black"),
        axis.ticks = element_line(color = "black", size =0.6),
        axis.ticks.length=unit(.15, "cm"),
        plot.title = element_text(size=13, hjust=0.5),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background = element_blank(),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.background = element_blank())

#Histograms are not good for distributions across groups
#cells have a much higher RIN compared to who blood.The obervations probably come from the number of cells that were sampled  
```

Q7
```{r}
#Visualize the number of genes detected per sample, stratifying by tissue
#genes detected is SMGNSDTC

ggplot(data = df_TruSeq, mapping = aes (x = SMTSD, y = SMGNSDTC))+
  geom_point() +
  xlab("Tissue sample") +
  ylab("Number of genes detected") +

  theme(axis.text=element_text(size=10, color="black"),
        axis.text.x=element_text(angle = 90),
        axis.title=element_text(size=13),
        axis.line = element_line(color="black"),
        axis.ticks = element_line(color = "black", size =0.6),
        axis.ticks.length=unit(.15, "cm"),
        plot.title = element_text(size=13, hjust=0.5),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background = element_blank(),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.background = element_blank())

#Testis tissue sample has a high number of genes detected. This could be because of a high number of single read cells going into the dataset? 
```

Q8
```{r}
#Plot the relationship between ischemic time and RIN. SMTSISCH
#Create sub-panels that stratify the data by tissue using facet_wrap(). 
#Resize points to size = 0.5 and set the opacity to alpha = 0.5. 
#Add linear trend lines to your plot with geom_smooth(method = "lm").


ggplot(data = df_TruSeq, mapping = aes( x = SMRIN, y = SMTSISCH)) +
  geom_point(size = 0.5, alpha = 0.5) +
  xlab("RIN") +
  ylab("Ischemic time (min)") +
  geom_smooth(method = "lm") +
  facet_wrap( ~ SMTSD) +

  theme(axis.text=element_text(size=10, color="black"),
        axis.title=element_text(size=13),
        axis.line = element_line(color="black"),
        axis.ticks = element_line(color = "black", size =0.6),
        axis.ticks.length=unit(.15, "cm"),
        plot.title = element_text(size=13, hjust=0.5),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background = element_blank(),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.background = element_blank())

#Broadly, amples are less degraded as ischemic time decreases. However, this is tissue specific. 
```


Q9
```{r}
#Copy answer from 8 above
#modify it to color your points by autolysis score (SMATSSCR). 

#Note that if we place aes(color = SMATSSCR) within the ggplot() portion of the code, it will attempt to apply this mapping to all geom_s, including geom_smooth. 

#To avoid this, place aes(color = SMATSSCR) within the geom_point() portion of the code.



ggplot(data = df_TruSeq, mapping = aes(x = SMRIN, y = SMTSISCH, color = SMATSSCR)) +
  geom_point(mapping = aes(x = SMRIN, y = SMTSISCH, color = SMATSSCR), size = 0.5, alpha = 0.5) +
  xlab("RIN") +
  ylab("Ischemic time (min)") +
  geom_smooth(mapping = aes(x = SMRIN, y = SMTSISCH), method = "lm", color = "black") +
  facet_wrap( ~ SMTSD) +

  theme(axis.text=element_text(size=10, color="black"),
        axis.title=element_text(size=13),
        axis.line = element_line(color="black"),
        axis.ticks = element_line(color = "black", size =0.6),
        axis.ticks.length=unit(.15, "cm"),
        plot.title = element_text(size=13, hjust=0.5),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background = element_blank(),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.background = element_blank())
```




